# Generated by Django 5.2.5 on 2025-08-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note_content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='task',
            new_name='note_task',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_task',
            new_name='sub_parent_task',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='task_category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='task_priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='subtask',
            name='sub_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
