# Generated by Django 5.2.5 on 2025-08-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmodels', '0002_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
